title: t(h)inker
author: Nguyễn Mai Hương / Sierra Nguyen
email: maihuongnguyen1603@gmail.com / nguyehuo@dickinson.edu
description: > # this means to ignore newlines until "baseurl:"
  I think about problems and tinker with them using data.
theme: minima

# social links
linkedin_username:  huongsierranguyen
github_username:  ngmaihuong

show_excerpts: false

plugins:
  - jemoji
