title: t(h)inker
author: Nguyễn Mai Hương / Sierra Nguyen
email: 
  nguyehuo@dickinson.edu
description: > # this means to ignore newlines until "baseurl:"
  I think about problems and tinker with them using data.
theme: minima

social_links:
  github:  ngmaihuong
  linkedin: huongsierranguyen

show_excerpts: false

plugins:
  - jemoji
